---
- name:
  hosts: prod-manager
  remote_user: ubuntu # define user account for ssh login
  serial: 1          # define the action will be done one by one
  gather_facts: yes
  tasks:
  - name: Check if "Swarm Mode" is enabled
    shell: docker info
    changed_when: False
    register: docker_info
    tags:
    - skip_ansible_lint # Suppressing the linter

  - name: Init "Swarm Mode" on the manager
    shell: docker swarm init > /home/ubuntu/swarm_init.cmd
    changed_when: False
    when: "docker_info.stdout.find('Swarm: active') == -1"

  - name: Retrieve the swarm command
    fetch:
      src: /home/ubuntu/swarm_init.cmd
      dest: /var/lib/jenkins/cluster/swarm_init.cmd
      flat: yes
    

- name:
  hosts: prod-worker-1
  remote_user: ubuntu # define user account for ssh login
  serial: 1          # define the action will be done one by one
  gather_facts: yes
  tasks:
  - name: Check if "Swarm Mode" is enabled on the worker
    shell: docker info
    changed_when: False
    register: docker_info
    tags:
    - skip_ansible_lint # Suppressing the linter

  - name: Copy swarm init command to Prod Server
    synchronize:
      delete: yes
      src: /var/lib/jenkins/cluster/swarm_init.cmd
      dest: /home/ubuntu/
    when: "docker_info.stdout.find('Swarm: active') == -1"

  - name: Joining the cluster
    shell: $(cat /home/ubuntu/swarm_init.cmd | grep "docker swarm join ")
    changed_when: False
    when: "docker_info.stdout.find('Swarm: active') == -1"

- name:
  hosts: prod-manager
  remote_user: ubuntu # define user account for ssh login
  serial: 1          # define the action will be done one by one
  gather_facts: yes
  tasks:
#   - name:
#     become: true
#     shell: bash /home/ubuntu/Deploy-CNA/scripts/client.sh 5000

#   - name: Pulling the docker images
#     shell: bash /home/ubuntu/Deploy-CNA/scripts/pull_images.sh

  - name: Launching the application
    shell: sudo /home/ubuntu/Deploy-CNA/docker_services.sh

- name: Send notification message via Slack
  hosts: localhost
  gather_facts: no
  tasks:
    - slack:
        token: T8DEDP22W/B8VCE6PNJ/fZS67hRnmBzaBTAVNvLYrDTO
        msg: 'Deployment of the App on the production environment'
        username: 'Deploy-App'
        color: good
        icon_url: 'https://www.ctl.io/knowledge-base/images/jenkins-stack-logo.png'
      delegate_to: localhost
